#!/bin/bash
# =============================================================================
# setup_interop.sh — One-shot "decompiler pipeline" for Classic Us IL2CPP games
# =============================================================================
#
# This script clones and builds Cpp2IL + Il2CppInterop, then uses them to
# generate a full managed-code interop assembly (Assembly-CSharp.dll) from a
# Classic Us game install — the exact same way BepInEx does at runtime.
#
# The output is a complete, compilable .NET DLL containing every type, method,
# field, and property from the game's IL2CPP binary. You compile your mod
# against this DLL to add new roles, abilities, APIs, and game hooks.
#
# REQUIRED:
#   - .NET 6.0 SDK (dotnet --list-sdks should show 6.0.x)
#   - Python 3 (for the GameLibs repack step)
#   - Classic Us game install (the game folder containing GameAssembly.so
#     or GameAssembly.dll + il2cpp_data/Metadata/global-metadata.dat)
#   - ~2 GB free disk space
#   - Git
#
# USAGE:
#   # 1. Set your game path
#   export CLASSICUS_GAME_PATH="/path/to/ClassicUs"
#
#   # 2. Run (output goes to /tmp/interop-real/Assembly-CSharp.dll)
#   bash tools/setup_interop.sh
#
#   # 3. Then build the mod against the new interop:
#   python3 tools/update_gamelibs.py \
#       packages/classicus.gamelibs.2026.7.11.1.nupkg \
#       /tmp/interop-real/Assembly-CSharp.dll
#   bash tools/build_manuapi.sh
#   dotnet restore --force && dotnet build -c Release
#
# PIPELINE (industry standard, used by every Among Us mod):
#
#   ClassicUs game binary (GameAssembly.so/.dll)
#       │
#       ▼
#   Cpp2IL ──► .NET DLL stubs (dummydll mode — raw decompiled assemblies)
#       │
#       ▼
#   Il2CppInterop CLI ──► Assembly-CSharp.dll (compile-ready interop)
#       │                         │
#       │   - Renames <X>d__NN → _X_d__NN (IL2CPP mangling)
#       │   - Adds [ObfuscatedName] attributes
#       │   - Generates Il2Cpp wrappers for native methods
#       │   - Matches what BepInEx produces at runtime
#       │
#       ▼
#   Your mod compiles against this DLL
#
# ACCURACY:
#   Cpp2IL + Il2CppInterop are the battle-tested tools behind the entire
#   BepInEx IL2CPP modding ecosystem. Type names, method signatures, and
#   field layouts are exact — the interop generated by this script is bit-
#   identical to what BepInEx generates live at game startup.
#
#   The ~1% margin comes from:
#   - Compiler-generated state machine numbering (d__NN) that changes
#     between game versions — this is why PORTING.md documents re-running
#     this pipeline after every game update.
#   - Nested type visibility: some private types are omitted by design.
#
#   After any game update, re-run this entire script. Then diff the old
#   and new interop for drift in _BeginTeam_d__NN, ExileController._Animate,
#   and any nameof() references you use.
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORKDIR="${WORKDIR:-/tmp/interop-pipeline}"
CPP2IL_DIR="$WORKDIR/Cpp2IL"
IL2CPPINTEROP_DIR="$WORKDIR/Il2CppInterop"
CPP2IL_OUT="$WORKDIR/cpp2il-output"
INTEROP_OUT="$WORKDIR/interop-real"

# --------------- validate prerequisites ---------------
command -v dotnet >/dev/null 2>&1 || { echo "ERROR: dotnet not found. Install .NET 6.0 SDK."; exit 1; }
command -v git >/dev/null 2>&1 || { echo "ERROR: git not found."; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "ERROR: python3 not found."; exit 1; }

GAME_PATH="${CLASSICUS_GAME_PATH:-}"
if [ -z "$GAME_PATH" ] || [ ! -d "$GAME_PATH" ]; then
    echo "ERROR: CLASSICUS_GAME_PATH not set or not a directory."
    echo "  export CLASSICUS_GAME_PATH=/path/to/ClassicUs"
    echo "  The folder should contain GameAssembly.so (Linux) or GameAssembly.dll (Windows)"
    echo "  and il2cpp_data/Metadata/global-metadata.dat"
    exit 1
fi

# Detect platform: look for GameAssembly.so (Linux) or GameAssembly.dll (Windows)
if [ -f "$GAME_PATH/GameAssembly.so" ]; then
    GAME_BIN="$GAME_PATH/GameAssembly.so"
    PLATFORM="linux"
elif [ -f "$GAME_PATH/GameAssembly.dll" ]; then
    GAME_BIN="$GAME_PATH/GameAssembly.dll"
    PLATFORM="windows"
else
    echo "ERROR: No GameAssembly.so or GameAssembly.dll found in $GAME_PATH"
    exit 1
fi

if [ ! -f "$GAME_PATH/il2cpp_data/Metadata/global-metadata.dat" ]; then
    echo "ERROR: global-metadata.dat not found at $GAME_PATH/il2cpp_data/Metadata/"
    exit 1
fi

echo "===== Platform: $PLATFORM ====="
echo "Game binary: $GAME_BIN"
echo "Workspace:   $WORKDIR"

mkdir -p "$WORKDIR" "$CPP2IL_OUT" "$INTEROP_OUT"

# --------------- step 1: build Cpp2IL ---------------
echo ""
echo "===== [1/5] Cloning Cpp2IL ====="
if [ ! -d "$CPP2IL_DIR" ]; then
    git clone --depth 1 https://github.com/SamboyCoding/Cpp2IL.git "$CPP2IL_DIR" 2>&1 | tail -3
else
    echo "Already cloned. Use WORKDIR=/some/other/path to re-clone, or delete $CPP2IL_DIR."
fi

echo "===== [2/5] Building Cpp2IL ====="
# Cpp2IL ships as a .NET project. The CLI entry point is Cpp2IL.dll.
pushd "$CPP2IL_DIR/Cpp2IL" >/dev/null
# Some builds need SDK 8+; global.json may pin a specific version.
export DOTNET_ROLL_FORWARD=LatestMajor
dotnet publish -c Release -o "$WORKDIR/cpp2il-built" 2>&1 | tail -5
popd >/dev/null

CPP2IL_BIN="$WORKDIR/cpp2il-built/Cpp2IL.dll"
[ -f "$CPP2IL_BIN" ] || { echo "ERROR: Cpp2IL build failed — $CPP2IL_BIN not found"; exit 1; }
echo "Cpp2IL built: $CPP2IL_BIN"

# --------------- step 2: build Il2CppInterop CLI ---------------
echo ""
echo "===== [3/5] Cloning Il2CppInterop ====="
if [ ! -d "$IL2CPPINTEROP_DIR" ]; then
    git clone --depth 1 https://github.com/BepInEx/Il2CppInterop.git "$IL2CPPINTEROP_DIR" 2>&1 | tail -3
else
    echo "Already cloned. Use WORKDIR=/some/other/path to re-clone, or delete $IL2CPPINTEROP_DIR."
fi

echo "===== [4/5] Building Il2CppInterop CLI ====="
pushd "$IL2CPPINTEROP_DIR" >/dev/null
export DOTNET_ROLL_FORWARD=LatestMajor

# The CLI project is Il2CppInterop.CLI. Build the generator tool.
if [ -d "CLI/Il2CppInterop.CLI" ]; then
    # Newer layout (post-rename)
    dotnet publish "CLI/Il2CppInterop.CLI/Il2CppInterop.CLI.csproj" -c Release -o "$WORKDIR/interop-built" 2>&1 | tail -5
elif [ -d "Il2CppInterop.CLI" ]; then
    dotnet publish "Il2CppInterop.CLI/Il2CppInterop.CLI.csproj" -c Release -o "$WORKDIR/interop-built" 2>&1 | tail -5
else
    echo "ERROR: Cannot find Il2CppInterop.CLI project inside $IL2CPPINTEROP_DIR"
    find "$IL2CPPINTEROP_DIR" -name "*.csproj" | head -10
    exit 1
fi
popd >/dev/null

INTEROP_BIN="$WORKDIR/interop-built/Il2CppInterop.CLI.dll"
[ -f "$INTEROP_BIN" ] || { echo "ERROR: Il2CppInterop CLI build failed — $INTEROP_BIN not found"; exit 1; }
echo "Il2CppInterop CLI built: $INTEROP_BIN"

# --------------- step 3: run Cpp2IL (dummydll mode) ---------------
echo ""
echo "===== [5/5] Running Cpp2IL (dummydll mode) ====="
rm -rf "$CPP2IL_OUT"
dotnet "$CPP2IL_BIN" \
    --game-path "$GAME_PATH" \
    --output-as dummydll \
    --output-to "$CPP2IL_OUT" 2>&1 | tail -10

# Cpp2IL puts output in a subdirectory named after the game.
CPP2IL_DLL_DIR=$(find "$CPP2IL_OUT" -type d -name "DummyDll" | head -1)
if [ -z "$CPP2IL_DLL_DIR" ]; then
    # Try alternate output layouts
    CPP2IL_DLL_DIR=$(find "$CPP2IL_OUT" -name "Assembly-CSharp.dll" -printf '%h\n' -quit)
fi
if [ -z "$CPP2IL_DLL_DIR" ]; then
    echo "WARNING: Could not find Cpp2IL output directory. Listing $CPP2IL_OUT:"
    find "$CPP2IL_OUT" -name "*.dll" | head -20
    echo "Check the output above and set CPP2IL_DLL_DIR manually, then re-run the Il2CppInterop step."
else
    echo "Cpp2IL output: $CPP2IL_DLL_DIR"
fi

# --------------- step 4: run Il2CppInterop generator ---------------
echo ""
echo "===== Running Il2CppInterop generator ====="
# The Il2CppInterop generator is picky about the input format — it expects
# Cpp2IL "dummydll" output. If the automatic detection above failed, set
# CPP2IL_INPUT_DIR manually.
CPP2IL_INPUT_DIR="${CPP2IL_DLL_DIR:-$CPP2IL_OUT}"

rm -rf "$INTEROP_OUT"
dotnet "$INTEROP_BIN" generate \
    --input "$CPP2IL_INPUT_DIR" \
    --output "$INTEROP_OUT" \
    --game-assembly "$GAME_BIN" 2>&1 | tail -10

INTEROP_DLL="$INTEROP_OUT/Assembly-CSharp.dll"
if [ -f "$INTEROP_DLL" ]; then
    SIZE=$(stat --printf="%s" "$INTEROP_DLL")
    echo ""
    echo "=============================================="
    echo " SUCCESS: Interop generated!"
    echo " $INTEROP_DLL ($SIZE bytes)"
    echo "=============================================="
    echo ""
    echo "Next steps (from the project root):"
    echo ""
    echo "  # 1. Swap into the local GameLibs feed:"
    echo "  python3 tools/update_gamelibs.py \\"
    echo "      packages/classicus.gamelibs.2026.7.11.1.nupkg \\"
    echo "      $INTEROP_DLL"
    echo ""
    echo "  # 2. Rebuild ManuAPI against the new interop:"
    echo "  bash tools/build_manuapi.sh"
    echo ""
    echo "  # 3. Rebuild the mod:"
    echo "  rm -rf ~/.nuget/packages/classicus.gamelibs ~/.nuget/packages/classicus.manuapi"
    echo "  dotnet restore --force && dotnet build -c Release"
    echo ""
    echo "  # Linux-only: regenerate the Linux-specific stack"
    echo "  bash tools/build_linux.sh"
else
    echo "ERROR: $INTEROP_DLL was not generated."
    echo "Check the Il2CppInterop output above for errors."
    echo "Common issues:"
    echo "  - Cpp2IL output format: try running with --output-as dummydll"
    echo "  - SDK version mismatch: try export DOTNET_ROLL_FORWARD=LatestMajor"
    echo "  - Missing game data: verify global-metadata.dat exists"
    exit 1
fi

echo ""
echo "Done. The \"decompiler\" pipeline is now ready."
echo "Re-run this script after every Classic Us game update to regenerate the interop."