#!/usr/bin/env python3
"""Replace Assembly-CSharp.dll inside the local GameLibs nupkg with the real
Classic Us 2026.8.9 interop generated by Cpp2IL + Il2CppInterop.

The published GameLibs (2026.7.11.1) is stale for game 8.9: the game dev
renamed IntroCutscene.<BeginTeam>d__35 -> d__36, breaking ManuAPI's Harmony
patch reference at runtime. Compiling everything against this updated package
makes the whole stack match the actual game binary.

Usage:
    python3 tools/update_gamelibs.py packages/classicus.gamelibs.2026.7.11.1.nupkg \\
        /path/to/interop/Assembly-CSharp.dll

Expects the *repacked* (forward-slash) local package as input — see
tools/repack_gamelibs.py for the initial normalization of the malformed
nuget.org download.
"""
import os
import shutil
import sys

from _nupkg_utils import rewrite_nupkg

PKG = sys.argv[1]       # local GameLibs nupkg to update (in place)
REAL_ACS = sys.argv[2]  # real 8.9 Assembly-CSharp.dll (Il2CppInterop output)

TARGET = "ref/net6.0/Assembly-CSharp.dll"

with open(REAL_ACS, "rb") as f:
    data = f.read()

tmp = PKG + ".tmp"
rewrite_nupkg(PKG, tmp, {TARGET: data})
shutil.move(tmp, PKG)
print(f"Updated {PKG}: {TARGET} <- {REAL_ACS} ({len(data)} bytes, signature stripped)")
